<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Activity;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $activities = [
            // 0-6 months activities
            [
                'title' => 'Tummy Time',
                'description' => 'Place baby on their tummy to strengthen neck and shoulder muscles',
                'min_age_months' => 0,
                'max_age_months' => 6,
                'category' => 'motor_skills',
                'duration' => '3-5 minutes, 2-3 times daily',
                'materials' => 'Soft mat or blanket, colorful toys',
                'instructions' => '1. Place baby on their stomach on a safe surface\n2. Get down at their level\n3. Use toys to encourage lifting head\n4. Start with short sessions and gradually increase',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Strengthens neck, shoulder, and arm muscles; prevents flat head syndrome; prepares for crawling',
            ],
            [
                'title' => 'High Contrast Visual Stimulation',
                'description' => 'Show baby black and white patterns to develop vision',
                'min_age_months' => 0,
                'max_age_months' => 4,
                'category' => 'sensory',
                'duration' => '5-10 minutes',
                'materials' => 'Black and white cards, pictures, or books',
                'instructions' => '1. Hold cards 8-12 inches from baby\'s face\n2. Move slowly from side to side\n3. Allow baby to focus on patterns\n4. Talk about what you\'re showing',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Develops visual tracking, focus, and brain development',
            ],
            [
                'title' => 'Gentle Baby Massage',
                'description' => 'Soothing massage for bonding and relaxation',
                'min_age_months' => 0,
                'max_age_months' => 12,
                'category' => 'sensory',
                'duration' => '10-15 minutes',
                'materials' => 'Baby-safe massage oil, soft towel, warm room',
                'instructions' => '1. Use gentle, slow strokes\n2. Start with legs and arms\n3. Massage tummy in circular motions\n4. Talk or sing softly during massage',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Promotes bonding, relaxation, better sleep, and body awareness',
            ],

            // 6-12 months activities
            [
                'title' => 'Peek-a-Boo',
                'description' => 'Classic game to teach object permanence',
                'min_age_months' => 6,
                'max_age_months' => 18,
                'category' => 'cognitive',
                'duration' => '5-10 minutes',
                'materials' => 'Your hands, cloth, or blanket',
                'instructions' => '1. Cover your face with hands\n2. Say "Where did I go?"\n3. Uncover and say "Peek-a-boo!"\n4. Let baby try covering their own face',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Teaches object permanence, cause and effect, social interaction',
            ],
            [
                'title' => 'Sensory Bottles',
                'description' => 'Create bottles with different materials for visual and auditory stimulation',
                'min_age_months' => 6,
                'max_age_months' => 24,
                'category' => 'sensory',
                'duration' => '10-15 minutes supervised',
                'materials' => 'Clear plastic bottles, rice, water, glitter, food coloring, small toys',
                'instructions' => '1. Fill bottles with different materials\n2. Seal tightly with strong glue\n3. Let baby shake and explore\n4. Always supervise play',
                'difficulty' => 'moderate',
                'developmental_benefits' => 'Visual tracking, cause and effect, auditory development',
            ],
            [
                'title' => 'Stacking Blocks',
                'description' => 'Build and knock down soft blocks',
                'min_age_months' => 9,
                'max_age_months' => 24,
                'category' => 'motor_skills',
                'duration' => '15-20 minutes',
                'materials' => 'Soft blocks or cups',
                'instructions' => '1. Show baby how to stack blocks\n2. Demonstrate knocking them down\n3. Let baby explore stacking\n4. Celebrate their efforts',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Hand-eye coordination, problem solving, spatial awareness',
            ],

            // 12-24 months activities
            [
                'title' => 'Shape Sorting',
                'description' => 'Match shapes to their corresponding holes',
                'min_age_months' => 12,
                'max_age_months' => 30,
                'category' => 'cognitive',
                'duration' => '10-15 minutes',
                'materials' => 'Shape sorter toy',
                'instructions' => '1. Show each shape and name it\n2. Demonstrate matching shape to hole\n3. Let toddler try independently\n4. Offer guidance when needed',
                'difficulty' => 'moderate',
                'developmental_benefits' => 'Problem solving, shape recognition, fine motor skills, spatial reasoning',
            ],
            [
                'title' => 'Color Hunt',
                'description' => 'Find objects of specific colors around the house',
                'min_age_months' => 18,
                'max_age_months' => 36,
                'category' => 'cognitive',
                'duration' => '15-20 minutes',
                'materials' => 'Basket or bag, household items',
                'instructions' => '1. Choose a color to find\n2. Walk around finding items of that color\n3. Collect items in basket\n4. Count and name the items found',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Color recognition, vocabulary, observation skills, counting',
            ],
            [
                'title' => 'Dancing to Music',
                'description' => 'Move and groove to different types of music',
                'min_age_months' => 12,
                'max_age_months' => 48,
                'category' => 'music',
                'duration' => '10-15 minutes',
                'materials' => 'Music player, various music genres',
                'instructions' => '1. Play different types of music\n2. Show different movements (jumping, spinning, marching)\n3. Let child move freely\n4. Dance together',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Gross motor skills, rhythm, self-expression, coordination',
            ],

            // 24-36 months activities
            [
                'title' => 'Playdough Creations',
                'description' => 'Sculpt and create with homemade or store-bought playdough',
                'min_age_months' => 24,
                'max_age_months' => 48,
                'category' => 'creative',
                'duration' => '20-30 minutes',
                'materials' => 'Playdough, cookie cutters, rolling pin, plastic tools',
                'instructions' => '1. Show how to roll, squish, and shape\n2. Provide tools and cutters\n3. Create simple shapes together\n4. Let child explore freely',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Fine motor skills, creativity, sensory development, hand strength',
            ],
            [
                'title' => 'Simple Puzzles',
                'description' => 'Complete age-appropriate jigsaw puzzles',
                'min_age_months' => 24,
                'max_age_months' => 48,
                'category' => 'cognitive',
                'duration' => '15-20 minutes',
                'materials' => 'Wooden puzzles with 4-12 pieces',
                'instructions' => '1. Start with edges or simple pieces\n2. Talk about the picture\n3. Provide hints when needed\n4. Celebrate completion',
                'difficulty' => 'moderate',
                'developmental_benefits' => 'Problem solving, spatial reasoning, patience, concentration',
            ],
            [
                'title' => 'Pretend Play - Kitchen',
                'description' => 'Cook and serve pretend meals',
                'min_age_months' => 24,
                'max_age_months' => 48,
                'category' => 'social',
                'duration' => '20-30 minutes',
                'materials' => 'Play kitchen, pretend food, pots and pans, dishes',
                'instructions' => '1. Set up play kitchen area\n2. Take orders for meals\n3. Pretend to cook together\n4. Serve and eat pretend food',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Imagination, social skills, language development, role-playing',
            ],

            // 36-48 months activities
            [
                'title' => 'Obstacle Course',
                'description' => 'Create indoor or outdoor obstacle course',
                'min_age_months' => 30,
                'max_age_months' => 48,
                'category' => 'motor_skills',
                'duration' => '20-30 minutes',
                'materials' => 'Cushions, tape, chairs, tunnels, cones',
                'instructions' => '1. Set up stations (crawl under, jump over, balance on)\n2. Demonstrate the course\n3. Time the child or race together\n4. Rearrange for variety',
                'difficulty' => 'moderate',
                'developmental_benefits' => 'Gross motor skills, coordination, following directions, confidence',
            ],
            [
                'title' => 'Story Time with Props',
                'description' => 'Read books and act out stories with props',
                'min_age_months' => 30,
                'max_age_months' => 48,
                'category' => 'language',
                'duration' => '15-20 minutes',
                'materials' => 'Books, stuffed animals, puppets, simple costumes',
                'instructions' => '1. Choose a favorite story\n2. Use props to act out characters\n3. Encourage child to participate\n4. Ask questions about the story',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Language skills, imagination, listening, comprehension, sequencing',
            ],
            [
                'title' => 'Nature Scavenger Hunt',
                'description' => 'Find items from a nature list outdoors',
                'min_age_months' => 30,
                'max_age_months' => 48,
                'category' => 'outdoor',
                'duration' => '30-45 minutes',
                'materials' => 'List with pictures, collection bag, magnifying glass',
                'instructions' => '1. Create picture list of items to find\n2. Go outside to safe area\n3. Search for items together\n4. Discuss discoveries',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Observation skills, nature appreciation, vocabulary, following directions',
            ],
            [
                'title' => 'Memory Matching Game',
                'description' => 'Find matching pairs of cards',
                'min_age_months' => 36,
                'max_age_months' => 48,
                'category' => 'cognitive',
                'duration' => '15-20 minutes',
                'materials' => 'Matching cards (8-12 pairs)',
                'instructions' => '1. Lay cards face down\n2. Take turns flipping two cards\n3. Find matching pairs\n4. Celebrate when matches are found',
                'difficulty' => 'moderate',
                'developmental_benefits' => 'Memory, concentration, turn-taking, pattern recognition',
            ],
            [
                'title' => 'Water Play Exploration',
                'description' => 'Explore water with various containers and toys',
                'min_age_months' => 18,
                'max_age_months' => 48,
                'category' => 'sensory',
                'duration' => '20-30 minutes',
                'materials' => 'Water table or basin, cups, funnels, sponges, toys',
                'instructions' => '1. Fill container with water\n2. Provide measuring cups and toys\n3. Demonstrate pouring and filling\n4. Always supervise closely',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Sensory exploration, hand-eye coordination, cause and effect, math concepts',
            ],
            [
                'title' => 'Building with Blocks',
                'description' => 'Construct towers, houses, and structures',
                'min_age_months' => 24,
                'max_age_months' => 48,
                'category' => 'motor_skills',
                'duration' => '20-30 minutes',
                'materials' => 'Various types of blocks (wooden, foam, magnetic)',
                'instructions' => '1. Start with simple structures\n2. Build together\n3. Talk about shapes and sizes\n4. Encourage creative building',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Spatial awareness, problem solving, creativity, fine motor skills',
            ],
            [
                'title' => 'Singing and Nursery Rhymes',
                'description' => 'Sing songs with hand motions and actions',
                'min_age_months' => 12,
                'max_age_months' => 48,
                'category' => 'music',
                'duration' => '10-15 minutes',
                'materials' => 'None needed (optional: music player)',
                'instructions' => '1. Choose familiar songs\n2. Add hand motions\n3. Encourage child to join in\n4. Repeat favorites often',
                'difficulty' => 'easy',
                'developmental_benefits' => 'Language development, memory, rhythm, social interaction',
            ],
        ];

        foreach ($activities as $activity) {
            Activity::create($activity);
        }
    }
}